#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

go install config
go install controller
go install lib/mysql
go install lib/seg
go install lib/spider
go install main

export GOPATH="$OLDGOPATH"

echo 'success'