#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

go install config
go install controller
go install lib/db
go install lib/spider
go install lib/mahonia
go build server.go

export GOPATH="$OLDGOPATH"

echo 'Server Start ...'
#./server
