#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

go install config
go install lib/spider
go install lib/db
go build tool.go

export GOPATH="$OLDGOPATH"

echo 'Build && Start ...'
./tool
